spring.application.name=ems

# Tạm thời tắt DB auto-config — sẽ xóa dòng này ở Module 4 khi cấu hình MySQL
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration